<?php

/**
 * @file
 * Primary module hooks for ReplayWebPage module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function replaywebpage_theme() {
  return [
    'replayweb_template' => [
      'variables' => [
        'playerBase' => NULL,
        'warcSource' => NULL,
        'baseUrl' => NULL,
        'height' => NULL,
        'width' => NULL,
        'noSandbox' => NULL,
        ],
    ],
  ];
}
